defaults:
#  origin :
#    url : 'https://github.com/RemoteConnectionManager/spack.git'
#    branches :
#      - 'clean/develop'
#closed      - 'pr/fix/flake8_configparser_backport'
#https://github.com/spack/spack/commit/f878c0cb5be8bc247ab85cffdacdcd6a9e1342f1

#  upstream :
#    prs : 
#merged     - '11646' # avoid fixed depnency of cmake from gnutls
#merged     - '8612' # Spack can be extended with external commands
#     - '7759' # enable using spack-installed packages as externals
#mybe break spack find     - '11871' #share spack source possibly among  users
#     - '11598' #Try to put spack source on local disk, so nothing on install point there
#introduce error on ccompiler find on marconi     - '11989' #Load compiler from modules
#merged     - '11372' #concretize environments together 
  runconfig: 'True'
  integration: 'True'
  upstream_update: 'True'
  rebase_update: 'True'
  cache: '../../cache'

logging_configs:
  loggers:
    cascade_yaml_config:
      level: WARNING
