
defaults:
  origin :
    branches :
#merged      - 'packages/fluxbox'
      - 'packages/fix/gdk-pixbuf_old_release'
      - 'packages/lxde-lxterminal'
      - 'packages/lxde-gpicview'
      - 'packages/lxde-leafpad'
      - 'packages/lxde-openbox'
      - 'packages/lxde-pcmanfm'
      - 'packages/lxde-tint2'
      - 'packages/xkeyboard-config'
      - 'packages/xkbcomp'
      - 'packages/libxi'
      - 'packages/pam'
      - 'packages/imagemagick'

#not needed any more?      - 'packages/mesa_update'
#not needed any more?      - 'packages/mesa-glu'
#not needed any more?      - 'packages/virtualgl'
#needed on redhat for build glib, see #6968 #6965
#fixed with merged 7493#      - 'pr/fix/glib_dtrace_pythonhome'






