# this is specific defaults  for different spack instances sharing same install path


defaults:
  integration : 'True'
  cache : '../cache'
  install : '../../install'
  clearconfig : 'True'
  origin :
    branches :
      - 'pr/fix/flake8_configparser_backport'
#merged      - 'pr/fix/perl-dependent-modules'


